# Generated by Django 5.1.4 on 2024-12-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0003_alter_flight_id_alter_passenger_id_alter_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
