# Generated by Django 5.1.4 on 2024-12-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0004_alter_place_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, choices=[('erkak', 'ERKAK'), ('ayol', 'AYOL')], max_length=20),
        ),
    ]
