# Generated by Django 5.1.4 on 2024-12-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0005_alter_passenger_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(choices=[('biznes', 'Ekanom'), ('biznes', 'Biznes'), ('birinchi', 'Birinchi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('KUTILMOQDA', 'Kutilmoqda'), ('TASDIQLANGAN', 'Tasdiqlangan'), ('BEKOR QILILGAN', 'Bekor_qilingan')], max_length=45),
        ),
    ]
